### PR TITLE
close all connections

### PR DESCRIPTION
**Pull request by csvigliano**
close all connections

### CODE REVIEW

**Comment by thiagodp** [comment]
Hi @csvigliano, thanks for the PR.

`pool.close()` should [close all the connections](https://github.com/tediousjs/node-mssql/issues/427). However, there is a [bug](https://github.com/tediousjs/node-mssql/issues/457) about that behavior in node-mssql. I'm considering to use a fork of`tediousjs`'s repo, since its outdated.

Whether the PR is applied, it would need to be reverted when the bug is fixed. So I will take a look in some forks to see if they fixed the issue and I will probably apply the PR if they didn't.

**Comment by csvigliano** [comment]
ok, thanks @thiagodp for your time.

**Comment by willmorgan** [comment]
@thiagodp Give it a go with v4.2.2 and let me know how you get on

**Comment by thiagodp** [comment]
Thanks @willmorgan, I upgraded in [v0.2.2](https://github.com/thiagodp/database-js-mssql/releases/tag/v0.2.2).

@csvigliano Did the upgrade solve your problem?

**Comment by csvigliano** [comment]
ok now I try it, thanks @thiagodp

**Comment by dhensby** [comment]
I don't think there's a bug in `node-mssql` around this? If someone has opened the global connection it needs closing and `mssql.close()` does that.

**Comment by thiagodp** [comment]
@dhensby What is the best approach? Close the `pool` *and* `mssql` ?

```js
 async close() {
        let pool = await this._pool();
        await pool.close();
        await mssql.close();
        this._isConnected = false;
    }
```

**Comment by dhensby** [comment]
@thiagodp yep

**Pull request closed without merging**
